### PR TITLE
Changes in the order of the lists in readme.md

### PR DESCRIPTION
**Pull request by gabriel19913**
Reordering the tables in readme.md in alphabetical order and adding an instruction in contribution.md saying to insert new items in this order.

### CODE REVIEW

**Comment by lucasgdb** [comment]
it has been labeled as "hacktoberfest-accepted", so it'll count for the event, but i'll update and merge it after the event is over! Thank you for this PR. :100:

**Comment by gabriel19913** [comment]
Ok, no problem. Thanks.

**Comment by lucasgdb** [comment]
no need to close this PR! It'll be used later

**Comment by gabriel19913** [comment]
Sorry, I think I closed by mistake hahahaah

**Pull request closed without merging**
