### PR TITLE
Added: GitHub cli & Marcdown

### PR DESCRIPTION
**Pull request by iarmankhan**

### CODE REVIEW

**Review by lucasgdb — CHANGES_REQUESTED** [review]
Please remove the file changes that were not changed (100644 -> 100755)

**Review by iarmankhan — COMMENTED** [review]
Hey, what should I change in here? I've just updated the postwoman to it's new URL and name (as the maintainer changed it a while ago) and added 2 new tools in the list.

**Comment by lucasgdb** [comment]
open another PR and do not change any other file instead of README.md

**Comment by iarmankhan** [comment]
Sure!

**Pull request closed without merging**
